<a href="https://colab.research.google.com/github/SachinScaler/PythonModuleApril24/blob/main/Dictionaries%7CLecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
dict1  = {}
print(type(dict1))

<class 'dict'>


In [ ]:
scaler_learners = {101:"Rohini", 102:"Rewati"}
len(scaler_learners)

2

In [ ]:
scaler_learners = {101:"Rohini", 102:"Rewati", 101:"Chanchal"}
len(scaler_learners)

2

In [ ]:
scaler_learners

{101: 'Chanchal', 102: 'Rewati'}

In [ ]:
scaler_learners = {101:"Rohini", 102:"Rewati", 103:"Chanchal", 104:"Sachine"}
print(scaler_learners)

{101: 'Rohini', 102: 'Rewati', 103: 'Chanchal', 104: 'Sachine'}


You can't perform indexing on Dict

In [ ]:
scaler_learners[0]

KeyError: 0

In [ ]:
# to access Values, we need to know the keys
print(scaler_learners[104])

Sachine


# update or Insert a Key

In [ ]:
# update
scaler_learners[104]="Sachin"
print(scaler_learners)

{101: 'Rohini', 102: 'Rewati', 103: 'Chanchal', 104: 'Sachin'}


In [ ]:
# insert
scaler_learners[105]="Swathy"
print(scaler_learners)

{101: 'Rohini', 102: 'Rewati', 103: 'Chanchal', 104: 'Sachin', 105: 'Swathy'}


#### print all keys without values

In [ ]:
scaler_learners.keys()

dict_keys([101, 102, 103, 104, 105])

In [ ]:
list(scaler_learners.keys())[-1]

105

 #### print all values  without keys

In [ ]:
scaler_learners.values()

dict_values(['Rohini', 'Rewati', 'Chanchal', 'Sachin', 'Swathy'])

####  Get Key Value Pairs as list of Tuples: Convert Dict

In [ ]:
scaler_learners.items()

dict_items([(101, 'Rohini'), (102, 'Rewati'), (103, 'Chanchal'), (104, 'Sachin'), (105, 'Swathy')])

In [ ]:
list(scaler_learners.items())[0]

(101, 'Rohini')

#### add another dictioary to dictionary

In [ ]:
scaler_learners_devops = {101:"Rohini", 102:"Rewati", 103:"Chanchal", 104:"Sachine"}
print(scaler_learners_devops)

{101: 'Rohini', 102: 'Rewati', 103: 'Chanchal', 104: 'Sachine'}


In [ ]:
scaler_learners_dsml= {201:"Nikhil", 202:"Pritesh", 203:"Udit"}
print(scaler_learners_dsml)

{201: 'Nikhil', 202: 'Pritesh', 203: 'Udit'}


In [ ]:
scaler_learners_devops | scaler_learners_dsml

{101: 'Rohini',
 102: 'Rewati',
 103: 'Chanchal',
 104: 'Sachine',
 201: 'Nikhil',
 202: 'Pritesh',
 203: 'Udit'}

In [ ]:
scaler_learners_devops.update(scaler_learners_dsml)

In [ ]:
scaler_learners_devops

{101: 'Rohini',
 102: 'Rewati',
 103: 'Chanchal',
 104: 'Sachine',
 201: 'Nikhil',
 202: 'Pritesh',
 203: 'Udit'}

In [ ]:
scaler_learners_devops

{101: 'Rohini',
 102: 'Rewati',
 103: 'Chanchal',
 104: 'Sachine',
 201: 'Nikhil',
 202: 'Pritesh',
 203: 'Udit'}

In [ ]:
scaler_learners_devops.pop(203)

'Udit'

In [ ]:
scaler_learners_devops

{101: 'Rohini',
 102: 'Rewati',
 103: 'Chanchal',
 104: 'Sachine',
 201: 'Nikhil',
 202: 'Pritesh'}

In [ ]:
scaler_learners_devops.pop()

TypeError: pop expected at least 1 argument, got 0

In [ ]:
del scaler_learners_devops[101]

In [ ]:
del scaler_learners_devops

In [ ]:
scaler_learners_devops

NameError: name 'scaler_learners_devops' is not defined

In [ ]:
scaler_learners_dsml= {201:"Nikhil", 202:"Pritesh", 203:"Udit"}

scaler_learners_dsml.remove

AttributeError: 'dict' object has no attribute 'remove'

In [ ]:
101 in scaler_learners_dsml

False

In [ ]:
all_leaners = {201:["Nikhil", "DSML"], 202:["Pritesh","Devops"], 203:["Udit","DSML"]}

In [ ]:
all_leaners

{201: ['Nikhil', 'DSML'], 202: ['Pritesh', 'Devops'], 203: ['Udit', 'DSML']}

In [ ]:
all_leaners[203]

['Udit', 'DSML']

In [ ]:
# all_leaners[203] = None

In [ ]:
all_leaners = {201:
 {"Name": "Nikhil", "Batch": "DSML"}}

In [ ]:
all_leaners

{201: {'Name': 'Nikhil', 'Batch': 'DSML'}}

In [ ]:
all_leaners[201]

{'Name': 'Nikhil', 'Batch': 'DSML'}

**Can you get and Print Batch of id 201**


**Convert the dictionary**

all_leaners = {201:["Nikhil", "DSML"], 202:["Pritesh","Devops"], 203:["Udit","DSML"]}

into same format as:
all_leaners = {201:{"Name": "Nikhil", "Batch": "DSML"}}


### Question

In [ ]:
scaler_learners_dsml= {201:"Nikhil", 202:"Pritesh", 203:"Udit"}

In [ ]:
scaler_learners_dsml[201]

'Nikhil'

In [ ]:
scaler_learners_dsml[101]

KeyError: 101

### way to avoid this error

In [ ]:
scaler_learners_dsml.get(201)

'Nikhil'

In [ ]:
print(scaler_learners_dsml.get(101))

None


In [ ]:
print(scaler_learners_dsml.get(101, "This Key is Not Present"))

This Key is Not Present


In [ ]:
print(scaler_learners_dsml.get(201, "This Key is Not Present"))

Nikhil


### Iterating

In [ ]:
dict1 = {'name': 'Thor Odinson',
     'age': 1500,
     'weapon': ['mjonir', 'stormbreaker'],
     'strongest': True}


for key in dict1:
    print(key)

name
age
weapon
strongest


In [ ]:
for key in dict1:
    print("Key: ",key)
    print("Value: ",dict1[key])

Key:  name
Value:  Thor Odinson
Key:  age
Value:  1500
Key:  weapon
Value:  ['mjonir', 'stormbreaker']
Key:  strongest
Value:  True


In [ ]:
for key,value in dict1.items():
    print("Key: ",key)
    print("Value: ",value)

Key:  name
Value:  Thor Odinson
Key:  age
Value:  1500
Key:  weapon
Value:  ['mjonir', 'stormbreaker']
Key:  strongest
Value:  True


In [ ]:
### in op

"age" in dict1

True

### Can you check if 1500 is present in values or not

In [ ]:
1500 in dict1.values()

True

In [ ]:
"age" in dict1

True

In [ ]:
dict1.keys()

dict_keys(['name', 'age', 'weapon', 'strongest'])

In [ ]:
"age" in dict1.keys() # same as membership on list

True

### Let's try key as dict

In [ ]:
dict1 = {101:{"Name":"Sachin", "Age":20}}

TypeError: unhashable type: 'dict'

In [ ]:
dict1 = {101:{"Name":"Sachin", "Age":20}}

In [ ]:
{"Name":"Sachin", "Age":20}

{'Name': 'Sachin', 'Age': 20}

{key:value, }

In [ ]:
dict1 = {["Sachin", "Age"]:20}

TypeError: unhashable type: 'list'

In [ ]:
dict1 = {20:["Sachin", "Age"]}

In [ ]:
dict1 = {("Sachin", "Age"):20} # no practical use

### Sorting

In [ ]:
list1 = [10,2,-3,5]
### sorted
sorted(list1)

[-3, 2, 5, 10]

In [ ]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [ ]:
sorted(list1, reverse=True)

[10, 5, 2, -3]

In [ ]:
list1 = ['grape', 'banana', 'apple']
sorted(list1)

['apple', 'banana', 'grape']

In [ ]:
list1 = ['grape', 'banana', 'apple' ,1 ]
sorted(list1)

TypeError: '<' not supported between instances of 'int' and 'str'

In [ ]:
my_dict = {'banana': 3, 'apple': 2, 'orange': 5, 'grape': 1}
print(my_dict)

{'banana': 3, 'apple': 2, 'orange': 5, 'grape': 1}


In [ ]:
sorted(my_dict)

['apple', 'banana', 'grape', 'orange']

In [ ]:
dict(sorted(my_dict.items()))

{'apple': 2, 'banana': 3, 'grape': 1, 'orange': 5}

In [ ]:
list1 = [[10,-5],[-4,11],[99,0]]
sorted(list1)

[[-4, 11], [10, -5], [99, 0]]

defaults sorts on 1st value i.e 0 index always for nested ds

In [ ]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [ ]:
list1 = [[10,-5],[-4,11],[99,0]]
sorted(list1, key = lambda x:x[1])

[[10, -5], [99, 0], [-4, 11]]

### Question: Can you change the below code to sort on Values

In [ ]:
dict(sorted(my_dict.items()))

{'apple': 2, 'banana': 3, 'grape': 1, 'orange': 5}

**VVI Question:.**
Write a function which takes string as input and creates a character frequency Dictionary:

There will be one key-value pair for each unique character.
Key will be the character name.
Value will be the count of the character inside the string.


```
Sample_input:
rrssstttt

Sample_Output
{
    "r": 2,
    "s": 3,
    "t": 4
}

```
